### ISSUE TITLE
getResultWithRange(), can you please precise?

### ISSUE THREAD

**Issue by rin67630** [wollewald/ADS1115_WE#18]
Could you please precise in the documentation how  getResultWithRange() behaves outside the boundaries min,max?
Extrapolate or clip?

**Comment by wollewald** [comment]
It extrapolates, since it uses the map function.

**Comment by rin67630** [comment]
Thank you, I mean it would be useful to mention that fact in the PDF list of commands, just to be complete and to avoid questions.
