### ISSUE TITLE
Example with 2 I2C addresses

### ISSUE THREAD

**Issue by rin67630** [wollewald/ADS1115_WE#22]
Suggestion:
I have found it out for myself, but it could be helpful to provide an example with two I2C addresses and some comment lines to explain how to set the address pin. 
_(e.g. I did not care with one module, I thought the address pin left floating provides the first address like the INA221, for the ADS1115 it must be wired to GND, Floating works also, but is off-label and possibly prone to dysfunction)_

Just to be nice to beginners not familiar with instantiation or the specific address technique of the ADS1115.
Regards.

**Comment by wollewald** [comment]
Good suggestion - done. For me the standard address (0x48) always worked without connecting to GND. But this may depend on the module. Maybe on some the address pin is pulled down to GND and on others not.
