### ISSUE TITLE
Question: wrong read value

### ISSUE THREAD

**Issue by lukasa1993** [wollewald/ADS1115_WE#26]
hello, i was using this lib to read 24v battery voltage started using it 6 month ago and it was working perfectly 1:1 with my multimeter but not after sitting turned off in drawer it measures wrong value there is about 0.4 volt difference between adc reading and multimeter reading on same pin on adc ground any way it could have been ruined ?

**Comment by wollewald** [comment]
Hi, can't imagine it's broken. In such a case I would expect no response, arbitrary value or always  the same. Difficult to say what's wrong when I don't have it on my desk. The first thing I would is checking all connections. Is there maybe a resistance on a line where shouldn't be any (due to a bad contact or so)?

**Comment by lukasa1993** [comment]
same difference for this particular value battery is stable right now so it doesn't fluctuate much only by 0.0001.

i checked connections and resistances all seems good + when i test same pin with multimeter value is exactly right but adc returns wrong

**Comment by wollewald** [comment]
Connecting two channels directly is something you could do reversibly I think. Whatever the result is, it will of course not solved the issue, it might just give an idea what the issue could be.

**Comment by lukasa1993** [comment]
thank you and sorry for weird case :)

**Comment by wollewald** [comment]
No problem,  I am happy to at least try to help. If you should find the problem I would still be interested to know what it was. Good luck!

**Comment by lukasa1993** [comment]
apparently ADC fails very weird way i replaced ads1115 board and all is good again

**Comment by wollewald** [comment]
Thanks for letting me know. Strange, indeed. I thought it would not be related with the ADS1115. Interesting learning.
