### ISSUE TITLE
Reduce code duplication

### ISSUE THREAD

**Issue by thijstriemstra** [wollewald/ADS1115_WE#9]
The new range functions (and others) duplicate/share a lot of code and, since space is scarce on these arduino devices, reducing duplication makes sense.

**Comment by thijstriemstra** [comment]
ping @wollewald

**Comment by wollewald** [comment]
Hi @thijstriemstra , it took a while, but now I have tidied up a little bit.

**Comment by thijstriemstra** [comment]
thanks!
